# é‚®ç®±ï¼ˆqqé‚®ç®±ï¼Œå› ä¸ºå‘éªŒè¯ç ä¸è¦é’±ï¼Œæ­£å¼é¡¹ç›®å¯ä»¥ç”¨å‘æ‰‹æœºéªŒè¯ç ğŸï¼Œè¦é’±ï¼‰
email:
  host: "smtp.qq.com"
  port: 587
  sender: "3423564182@qq.com"
  password: "qnybtryzviuycjba"
  protocol: "smtp"

# redis-0 å­˜å‚¨é‚®ç®±éªŒè¯ç 
# redis-1 å­˜å‚¨ç”¨æˆ·åŒtoken
# redis-2 risk-serverå­˜å‚¨ç”¨æˆ·ç™»å½•ipï¼Œagentå’ŒçŠ¶æ€ï¼ˆæˆåŠŸæˆ–å¤±è´¥ï¼‰
# é»˜è®¤è¿æ¥ redis-0
redis:
  host: "localhost"
  port: 6379
  password: ""        # æ²¡æœ‰å¯†ç ï¼Œç•™ç©º
  db: 0               # é»˜è®¤æ•°æ®åº“ 0

# mysql-user-server
mysql-user-server:
  host: "localhost"
  port: 3306
  user: "root"
  password: "tjp20040808"
  dbname: "b2c_user"

# mysql-log-server
mysql-log-server:
  host: "localhost"
  port: 3307
  user: "root"
  password: "tjp20040808"
  dbname_info: "b2c_log_info"
  dbname_warn: "b2c_log_warn"
  dbname_error: "b2c_log_error"

# mysql-risk-server
mysql-risk-server:
  host: "localhost"
  port: 3308
  user: "root"
  password: "tjp20040808"
  dbname: "b2c_risk"

# Kafka-log-server æ—¥å¿—æœåŠ¡kafkaé˜Ÿåˆ—
kafka-log-server:
  brokers:
    - "localhost:9092"
  group_id: "log-server"    # æ¶ˆè´¹è€…ç»„
  topic: "log-server"       # topic
